name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
      - name: Deploy (prod)
        run: vercel --prod --yes --token=$VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: team_IKIr2Kcs38KGo8Zs60yNtm7Y
          VERCEL_PROJECT_ID: prj_Jty8omrqowrzzcsFjqp2n4Jcn9PR
